name: serviceflow
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: 0.20.2
  flutter_svg: ^2.0.9
  provider: ^6.1.2
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  window_manager: ^0.3.8
  url_launcher: ^6.2.6
  table_calendar: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/service_flow_logo.svg
